In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

In [11]:
data = pd.read_excel("./data/predict_population.xlsx")
data.columns = ['성별','시점','연령별','인구수']
data["총인구수"] = data.groupby(['성별','시점'])['인구수'].transform(sum)
data['인구비율'] = np.round(data['인구수'] / data['총인구수'] * 100,4)
data

      성별    시점       연령별      인구수      총인구수    인구비율
0     전체  2022    0 - 4세  1494041  51672569  2.8914
1     전체  2022    5 - 9세  2142084  51672569  4.1455
2     전체  2022  10 - 14세  2311839  51672569  4.4740
3     전체  2022  15 - 19세  2287873  51672569  4.4276
4     전체  2022  20 - 24세  3105237  51672569  6.0094
...   ..   ...       ...      ...       ...     ...
3208  여자  2072  80 - 84세  1471905  18013264  8.1712
3209  여자  2072  85 - 89세  1312037  18013264  7.2837
3210  여자  2072  90 - 94세  1063593  18013264  5.9045
3211  여자  2072  95 - 99세   479859  18013264  2.6639
3212  여자  2072   100세 이상   152406  18013264  0.8461

[3213 rows x 6 columns]

In [14]:
data.to_excel('./output/인구예측수.xlsx',index=False)